name: weather
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.5.0+1
  flutter_bloc: ^8.1.6
  logger: ^2.4.0
  injectable: ^2.4.4
  get_it: ^7.6.7
  json_annotation: ^4.9.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.1
  intl: ^0.19.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

